//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentView
    {
        public int code { get; set; }
        public string name { get; set; }
        public string full_name { get; set; }
        public string Expr1 { get; set; }
        public string reg_number { get; set; }
        public System.DateTime issue_date { get; set; }
        public System.DateTime return_date { get; set; }
        public double rental_cost { get; set; }
        public double payment_mark { get; set; }
        public Nullable<int> rental_period { get; set; }
        public Nullable<int> option_code1 { get; set; }
        public Nullable<int> option_code2 { get; set; }
        public Nullable<int> option_code3 { get; set; }
        public int vehicle_code { get; set; }
    }
}
